name: modul_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # İkonlar ve Temel Paketler
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  intl: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase (Kararlı ve Uyumlu Sürümler)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Dosya ve Paylaşım
  pdf: ^3.10.0
  printing: ^5.11.0
  excel: ^4.0.0
  path_provider: ^2.1.2
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true